name: Metrics
on:
  schedule: [{cron: "0 0 * * 1"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    steps:

      - name: perfil
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: southamerica/Ecuador

