name: Metrics
on:
  schedule: [{cron: "0 0 * * 1"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-examples:
    runs-on: ubuntu-latest
    steps:

      - name: perfil
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: southamerica/Ecuador
          
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Featured star list languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome

      - name: Labels
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 19

